name: lint

on:
  push:
    paths: [ 'en/**.json' ]
  pull_request:
    paths: [ 'en/**.json' ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up node"
        uses: actions/setup-node@v2.4.0

      - name: "Install"
        run: npm install jsonlint -g

      - name: "Lint"
        run: jsonlint en/messages.json
